spring:
  application:
    name: spring-batch-gradle-sample
  config:
    import:
      - classpath:config/app-batch.yml
      - classpath:config/app-datasource.yml
  batch:
    jdbc:
      initialize-schema: always
    job:
      name: billingNdjsonJob
