CREATE TABLE IF NOT EXISTS billing (
    id BIGINT PRIMARY KEY,
    billing_no VARCHAR(40) NOT NULL,
    processed BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS billing_detail (
    billing_id BIGINT PRIMARY KEY,
    amount DECIMAL(15, 2) NOT NULL,
    due_date DATE NOT NULL,
    CONSTRAINT fk_billing_detail_billing FOREIGN KEY (billing_id) REFERENCES billing(id)
);

CREATE TABLE IF NOT EXISTS bill_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    billing_id BIGINT NOT NULL UNIQUE,
    payload_ndjson CLOB NOT NULL,
    created_at TIMESTAMP NOT NULL
);
