CREATE TABLE IF NOT EXISTS billing (
    id BIGINT PRIMARY KEY,
    billing_no VARCHAR(40) NOT NULL,
    processed BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS billing_detail (
    billing_id BIGINT PRIMARY KEY,
    amount DECIMAL(15, 2) NOT NULL,
    due_date DATE NOT NULL,
    CONSTRAINT fk_billing_detail_billing FOREIGN KEY (billing_id) REFERENCES billing(id)
);

CREATE TABLE IF NOT EXISTS bill_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    billing_id BIGINT NOT NULL UNIQUE,
    payload_ndjson CLOB NOT NULL,
    created_at TIMESTAMP NOT NULL
);

DELETE FROM bill_data;
DELETE FROM billing_detail;
DELETE FROM billing;

INSERT INTO billing (id, billing_no, processed) VALUES
(1, 'BILL-0001', FALSE),
(2, 'BILL-0002', FALSE),
(3, 'BILL-0003', FALSE);

INSERT INTO billing_detail (billing_id, amount, due_date) VALUES
(1, 12000.50, DATE '2026-04-01'),
(2, 8000.00, DATE '2026-04-02'),
(3, 4300.10, DATE '2026-04-03');
